services:
  frontend:
    image: aime-fe_frontend
    container_name: aime-frontend
    ports:
      - "3000:80"
    # depends_on:
    #   - backend
    # volumes:
    #   - ./web_ui/nginx.conf:/etc/nginx/conf.d/default.conf:rw
    #   - ./web_ui:/usr/share/nginx/html:rw
    volumes:
      - ./api/files:/api/files
    networks:
      - aimemasking_network

  backend:
    image: aimemasking_be:latest
    # image: aimemasking_be:20250716
    container_name: aimemasking_be
    ports:
      - "1234:1234"
    #  - "1200:1200"
    volumes:
      - ./model_checkpoint:/app/model_checkpoint
      - ./api/files:/app/api/files
    mem_limit: 2g
    mem_reservation: 1g
    cpus: 4.0
    networks:
      - aimemasking_network


  postgres:
    image: postgres:15
    container_name: aimemasking_postgres
    environment:
      POSTGRES_USER: aimemasking
      POSTGRES_PASSWORD: aime12345
      POSTGRES_DB: aimemasking_db
    ports:
      - "5400:5432"
    volumes:
      - ./db/postgres_data:/var/lib/postgresql/data
    networks:
      - aimemasking_network
networks:
  aimemasking_network:
    driver: bridge