version: "3.8"

services:
  frontend:
    build: .
    container_name: aime-frontend
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=http://backend:1235/api
    depends_on:
      - backend
    networks:
      - aime-network

  backend:
    image: aimemasking_be:latest
    container_name: aime-backend
    ports:
      - "1235:1235"
    restart: unless-stopped
    networks:
      - aime-network

networks:
  aime-network:
    driver: bridge
